name: NIDM-specs unit tests

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7]
      fail-fast: false
    runs-on: ${{ matrix.os }}


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update build tools
      run: python -m pip install --upgrade pip setuptools

    - name: Install NIDM Results repo
      run: pip install git+git://github.com/incf-nidash/nidmresults.git

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: unit tests
      run: |
        python -m unittest discover -s ./nidm/nidm-results/test/ -p '[t|T]est*.py'
        python test/test_specifications.py